apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiapp-deployment
  namespace: team-riker
spec:
  selector:
    matchLabels:
      app: skiapp
  replicas: 2
  template:
    metadata:
      labels:
        app: skiapp
    spec:
      containers:
        - name: skiapp
          image: sharepointoscar/skiapp:070c69bba3141a45f488bd13e296dd3587ddb934
          #image: alexroman/skiapp:0.0.2
          env:
            - name: ENABLE_TRACING
              value: 'true'
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
